function init () {

const inquirer = require('inquirer');
const fs = require('fs'); 
const generate = require('./utils/generateMarkdown.js');
const path = require('path');
//this is my script. WESLEY DUBOSE.
inquirer
  //Inquirer prompt used to ask questions and collect answers.
  //Type describes the type of response the program will ask for
  //Message is what will be displayed in the command line to describe what should be written in the response
  //name is the key that is associated to the response so it can be referenced to when recalling the responses.
  .prompt([
    { 
      type: "input",
      message: "What would you like to title your document?",
      name: "title",  
         },
    { 
      type: "input",
      message: "Please describe the project:",
      name: "description",  
         },
    {
       type: "input",
       message: "How do you Install your application?",
       name: "installation",
    },
    {
        type: "input",
        message: "How do you Use your application?",
        name: "usage",
    },
    {
        type: "input",
        message: "What are the contribution guidelines for this project?",
        name: "contributing",
    },
   {
        type: "input",
        message: "How do users perform tests for this project?",
        name: "tests"
    },
    {
      type: "checkbox",
      message: "What License did you use for this repository?",
      choices: ["MIT", "GNU General Public License 2.0", "Apache License 2.0", "GNU General Public License 3.0"],
      name: "license",
    },
    {
        type: "input",
        message: "What is your GitHub username?",
        name: "github"
    },
    {
        type: "input",
        message: "What is your email address?",
        name: "email"
    },
    {
      type: "input",
      message: "Provide instructions for reaching out with questions:",
      name: "reachOut"
    }
  ])
  //after questions have been answered, then a README.md file is generated using the node filesystem or fs module.
  //this function generates a README.md file with the content of generate(response)
  //generate(response) is using the module that was imported at the top of the page, and passing the responses from the inquirer prompt.
  //the module returns the content of the README.md file after filling in the responses.
  //the content returned from the generate(response) module is set as the content of the file being generated by the node filesystem module
  .then((response) => {
    return fs.writeFileSync(path.join (process.cwd(), "README.md"), generate(response));
  });
}

init();
